//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsf_service_template_net6.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Program {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Program() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dsf-service-template-net6.Resources.Program", typeof(Program).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Η παρούσα αποτελεί δήλωση προσβασιμότητας για την υπηρεσία «Βοήθημα Τοκετού» του Υπουργείου Εργασίας και Κοινωνικών Ασφαλίσεων.&lt;/p&gt;
        ///      &lt;h2&gt;Κατάσταση συμμόρφωσης&lt;/h2&gt;
        ///      &lt;p&gt;Οι Οδηγίες Προσβασιμότητας Περιεχομένου (&lt;a href=&quot;https://www.w3.org/TR/WCAG21/&quot; target=&quot;_blank&quot;&gt;WCAG&lt;/a&gt;) καθορίζουν απαιτήσεις για σχεδιαστές και προγραμματιστές για τη βελτίωση της προσβασιμότητας των ατόμων με αναπηρίες. Καθορίζουν τρία επίπεδα συμμόρφωσης: Επίπεδο A, Επίπεδο AA, και Επίπεδο AAA. Η υπηρεσία συμμορφώνεται με [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AccessibilityStatement_Instructions {
            get {
                return ResourceManager.GetString("AccessibilityStatement_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δήλωση προσβασιμότητας.
        /// </summary>
        public static string AccessibilityStatement_Title {
            get {
                return ResourceManager.GetString("AccessibilityStatement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βοήθημα Τοκετού.
        /// </summary>
        public static string Apply_For_ChildBirth_Grant_Title {
            get {
                return ResourceManager.GetString("Apply_For_ChildBirth_Grant_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πίσω.
        /// </summary>
        public static string BackButton_Link {
            get {
                return ResourceManager.GetString("BackButton_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πλοήγηση από το πληκτρολόγιο.
        /// </summary>
        public static string Container_content {
            get {
                return ResourceManager.GetString("Container_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσβασιμότητα.
        /// </summary>
        public static string Footer_Accessibility_Statement {
            get {
                return ResourceManager.GetString("Footer_Accessibility_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προστασία Προσωπικών Δεδομένων.
        /// </summary>
        public static string Footer_Cookey_Policy {
            get {
                return ResourceManager.GetString("Footer_Cookey_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κυπριακή Δημοκρατία, 2022.
        /// </summary>
        public static string Footer_CopyRight {
            get {
                return ResourceManager.GetString("Footer_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όροι Χρήσης.
        /// </summary>
        public static string Footer_Privacy_Statement {
            get {
                return ResourceManager.GetString("Footer_Privacy_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogOut_SignOut {
            get {
                return ResourceManager.GetString("LogOut_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παίρνεις βοήθημα μέχρι €581 όταν γεννήσεις. Μάθε τι θα χρειαστείς για να είσαι δικαιούχος και πώς να υποβάλεις αίτηση διαδικτυακά..
        /// </summary>
        public static string Meta_Description {
            get {
                return ResourceManager.GetString("Meta_Description", resourceCulture);
            }
        }
    }
}
